### ISSUE TITLE
Sitemap addon: Sitemap generation error when using i18n

### ISSUE THREAD

**Issue by boazpoolman** [pluginpal/strapi-webtools#158]
### Describe the bug

Whenever I create a content type with localization enabled, create some (translated) entries for it, and try to generate the sitemap I get the following error:

```
  TypeError: Cannot read properties of undefined (reading 'replace')
      at otag (/Users/boazpoolman/Code/boazpoolman/strapi/strapi-plugin-webtools/node_modules/sitemap/dist/lib/sitemap-xml.js:22:14)
      at element (/Users/boazpoolman/Code/boazpoolman/strapi/strapi-plugin-webtools/node_modules/sitemap/dist/lib/sitemap-xml.js:44:16)
      at /Users/boazpoolman/Code/boazpoolman/strapi/strapi-plugin-webtools/node_modules/sitemap/dist/lib/sitemap-item-stream.js:128:49
      at Array.forEach (<anonymous>)
      at SitemapItemStream._transform (/Users/boazpoolman/Code/boazpoolman/strapi/strapi-plugin-webtools/node_modules/sitemap/dist/lib/sitemap-item-stream.js:127:20)
      at Transform._write (node:internal/streams/transform:175:8)
      at writeOrBuffer (node:internal/streams/writable:447:12)
      at _write (node:internal/streams/writable:389:10)
      at Writable.write (node:internal/streams/writable:393:10)
      at SitemapStream._transform (/Users/boazpoolman/Code/boazpoolman/strapi/strapi-plugin-webtools/node_modules/sitemap/dist/lib/sitemap-stream.js:74:24)
```

### Steps to reproduce the behavior

1. Enable localization for a content type
2. Create some entries for that content type
3. Translate those entries
4. Add the content type to the sitemap URL bundles
5. Generate the sitemap

### Expected behavior

A sitemap would be generated like normal.

### System

- Node.js version: 20.8.1
- NPM version: 10.1.0
- Strapi version: 4.19.0
- Plugin version: master
- Database: Postgres
- Operating system: MacOS

**Comment by boazpoolman** [comment]
This was released with `v1.0.0-beta.9` of the sitemap addon.
